# ==============================================================================
# STEP 20: NUMBERS-FOR-THESIS -- profile-level tables for chapters 4-7
# Thesis: "Invisible Profiles" - Bocconi MSc EMIT (course 20570, Prof. Trentini)
#
# Reads the canonical RDS files produced by steps 7-11 and emits a single
# markdown file `v9/outputs/thesis_numbers.md` containing every table the
# thesis text needs to quote (chapter-by-chapter). The script does NOT
# recompute any number: it only re-assembles what the pipeline already knows.
#
# INPUT  : step7_italy_with_clusters.rds, step7_italy_profile_table.rds,
#          step8_sweden_with_clusters.rds, step8_sweden_profile_table.rds,
#          step9_cross_country_gap.rds, step9_matched_pairs_tests.rds,
#          step11_italy_with_healthcare.rds, step11_sweden_with_healthcare.rds,
#          step11_healthcare_italy_isolati_vs_sociali.rds,
#          step11_healthcare_cross_country.rds
# OUTPUT : v9/outputs/thesis_numbers.md
# ==============================================================================

suppressMessages({
  library(dplyr)
  library(tidyr)
  library(haven)   # zap_labels in case cluster RDS carries labelled columns
})

data_path <- "~/Desktop/SHARE DATASET/DATASET RESEARCH"
out_dir   <- file.path(data_path, "v9", "outputs")
out_md    <- file.path(out_dir, "thesis_numbers.md")

italy_clust    <- readRDS(file.path(out_dir, "step7_italy_with_clusters.rds"))
sweden_clust   <- readRDS(file.path(out_dir, "step8_sweden_with_clusters.rds"))
italy_ptable   <- tryCatch(readRDS(file.path(out_dir, "step7_italy_profile_table.rds")),
                           error = function(e) NULL)
sweden_ptable  <- tryCatch(readRDS(file.path(out_dir, "step8_sweden_profile_table.rds")),
                           error = function(e) NULL)
cross_gap      <- tryCatch(readRDS(file.path(out_dir, "step9_cross_country_gap.rds")),
                           error = function(e) NULL)
matched_tests  <- tryCatch(readRDS(file.path(out_dir, "step9_matched_pairs_tests.rds")),
                           error = function(e) NULL)
italy_hc       <- tryCatch(readRDS(file.path(out_dir, "step11_italy_with_healthcare.rds")),
                           error = function(e) NULL)
sweden_hc      <- tryCatch(readRDS(file.path(out_dir, "step11_sweden_with_healthcare.rds")),
                           error = function(e) NULL)
iso_vs_soc     <- tryCatch(readRDS(file.path(out_dir, "step11_healthcare_italy_isolati_vs_sociali.rds")),
                           error = function(e) NULL)
hc_cross       <- tryCatch(readRDS(file.path(out_dir, "step11_healthcare_cross_country.rds")),
                           error = function(e) NULL)

# Profile orders used across the thesis
profile_order_italy  <- c("Fragile Resigned", "Fragile Depressed",
                          "Moderate Isolated", "Traditional Social",
                          "Connected Active")
profile_order_sweden <- c("Fragile", "Social Decline", "Moderate",
                          "Asset Rich", "Wealthy Digital", "Connected Wealthy")

# Pull a numeric column as plain numeric (strips haven_labelled)
num <- function(x) as.numeric(haven::zap_labels(x))

# Helper: pretty rounding with locale-safe dot
rnd <- function(x, d = 2) formatC(round(x, d), format = "f", digits = d)

# ---- Markdown emitter ------------------------------------------------------
con <- file(out_md, open = "w")
wl  <- function(...) cat(..., "\n", file = con, sep = "")

wl("# Thesis numbers (auto-generated by 20_thesis_tables.R)")
wl("")
wl("_Generated on_: ", format(Sys.time(), "%Y-%m-%d %H:%M"))
wl("")
wl("This file is the single source of truth for every profile-level number")
wl("quoted in Chapters 4, 5, 6, 7. Re-run the script after any change to the")
wl("upstream pipeline and copy the tables below into the LaTeX chapters.")
wl("")

# ===========================================================================
# CHAPTER 4 -- ITALIAN PROFILES
# ===========================================================================
wl("## Chapter 4 -- Italian profiles")
wl("")
wl("**Sample:** n = ", nrow(italy_clust), " after listwise + Mahalanobis screen.")
wl("")

italy_clust$profile <- factor(as.character(italy_clust$profile),
                              levels = profile_order_italy)

# Table 4.3 skeleton: size and means on key variables
key_vars_it <- intersect(c("age", "yedu", "internet", "casp", "loneliness",
                            "hope_future", "sn_size_w9", "lifesat"),
                          names(italy_clust))

tab_it <- italy_clust %>%
  filter(!is.na(profile)) %>%
  group_by(profile) %>%
  summarise(
    n = n(),
    pct = 100 * n() / nrow(italy_clust),
    across(all_of(key_vars_it), ~ mean(num(.x), na.rm = TRUE)),
    .groups = "drop"
  )

wl("### Table 4.1 -- Italian profile sizes and cluster means")
wl("")
header_it <- c("Profile", "n", "%", key_vars_it)
wl("| ", paste(header_it, collapse = " | "), " |")
wl("|", paste(rep("---", length(header_it)), collapse = "|"), "|")
for (i in seq_len(nrow(tab_it))) {
  row <- tab_it[i, ]
  vals <- c(as.character(row$profile),
            as.character(row$n),
            rnd(row$pct, 1),
            vapply(key_vars_it, function(v) rnd(row[[v]], 2), character(1)))
  wl("| ", paste(vals, collapse = " | "), " |")
}
wl("")

# ===========================================================================
# CHAPTER 5 -- SWEDISH PROFILES + CROSS-COUNTRY GAPS
# ===========================================================================
wl("## Chapter 5 -- Swedish profiles and cross-country gap")
wl("")
wl("**Sample:** n = ", nrow(sweden_clust), " after listwise + Mahalanobis screen (258 outliers removed).")
wl("")

sweden_clust$profile <- factor(as.character(sweden_clust$profile),
                               levels = profile_order_sweden)

key_vars_se <- intersect(c("age", "yedu", "internet", "casp", "loneliness",
                            "hope_future", "sn_size_w9", "lifesat"),
                          names(sweden_clust))
tab_se <- sweden_clust %>%
  filter(!is.na(profile)) %>%
  group_by(profile) %>%
  summarise(
    n = n(),
    pct = 100 * n() / nrow(sweden_clust),
    across(all_of(key_vars_se), ~ mean(num(.x), na.rm = TRUE)),
    .groups = "drop"
  )

wl("### Table 5.1 -- Swedish profile sizes and cluster means")
wl("")
header_se <- c("Profile", "n", "%", key_vars_se)
wl("| ", paste(header_se, collapse = " | "), " |")
wl("|", paste(rep("---", length(header_se)), collapse = "|"), "|")
for (i in seq_len(nrow(tab_se))) {
  row <- tab_se[i, ]
  vals <- c(as.character(row$profile),
            as.character(row$n),
            rnd(row$pct, 1),
            vapply(key_vars_se, function(v) rnd(row[[v]], 2), character(1)))
  wl("| ", paste(vals, collapse = " | "), " |")
}
wl("")

if (!is.null(cross_gap)) {
  wl("### Table 5.2 -- Cross-country gap on matched pairs (SE minus IT)")
  wl("")
  wl("```")
  print(cross_gap)
  wl("```")
  wl("")
}
if (!is.null(matched_tests)) {
  wl("### Matched-pair tests (Welch's t)")
  wl("")
  wl("```")
  print(matched_tests)
  wl("```")
  wl("")
}

# ===========================================================================
# CHAPTER 6 -- ROBUSTNESS (profile sizes confirming Table 6 in the chapter)
# ===========================================================================
wl("## Chapter 6 -- Profile sizes cross-referenced")
wl("")
wl("| Profile                    | Italy n | Sweden n |")
wl("|----------------------------|---------|----------|")
for (p in profile_order_italy) {
  n_it <- sum(italy_clust$profile == p, na.rm = TRUE)
  wl("| ", p, " | ", n_it, " | --- |")
}
for (p in profile_order_sweden) {
  n_se <- sum(sweden_clust$profile == p, na.rm = TRUE)
  wl("| ", p, " | --- | ", n_se, " |")
}
wl("| **Total**                  | **", nrow(italy_clust), "** | **", nrow(sweden_clust), "** |")
wl("")

# ===========================================================================
# CHAPTER 7 -- HEALTHCARE UTILIZATION
# ===========================================================================
wl("## Chapter 7 -- Healthcare utilization")
wl("")
if (!is.null(italy_hc)) {
  wl("**Italy healthcare-merged sample:** n = ", nrow(italy_hc),
     " out of ", nrow(italy_clust),
     " (", rnd(100 * nrow(italy_hc) / nrow(italy_clust), 1), "% match rate).")
  wl("")
}
if (!is.null(sweden_hc)) {
  wl("**Sweden healthcare-merged sample:** n = ", nrow(sweden_hc),
     " out of ", nrow(sweden_clust),
     " (", rnd(100 * nrow(sweden_hc) / nrow(sweden_clust), 1), "% match rate).")
  wl("")
}
if (!is.null(iso_vs_soc)) {
  wl("### Moderate Isolated vs Traditional Social (Italy)")
  wl("")
  wl("```")
  print(iso_vs_soc)
  wl("```")
  wl("")
}
if (!is.null(hc_cross)) {
  wl("### Healthcare utilization, cross-country aggregate")
  wl("")
  wl("```")
  print(hc_cross)
  wl("```")
  wl("")
}

close(con)

cat("============================================================\n")
cat("STEP 20 COMPLETE -- thesis numbers assembled\n")
cat("============================================================\n")
cat("  output: ", out_md, "\n", sep = "")
cat("  open in editor and paste the relevant sections into the LaTeX chapters.\n")
